app = "webtorrent-webrtc-party"
primary_region = "iad"

[env]
PORT = "8080"
APP_PASSWORD = "changeme" # Set your password here or in the Fly dashboard.

[[services]]
  protocol = "tcp"
  internal_port = 8080
  ports = [{ port = 80 }, { port = 443 }]
  force_https = true

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "10s"